apiVersion: v1
description: scala development running on Kubernetes
name: scala
maintainers:
  - name: jaohaohsuan
icon: "http://www.synycs.com/images/scala-logo2.png"
version: 0.2.0
tillerVersion: ">2.3.1"
appVersion: 2.11
