# Default values for scala.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: henryrao/sbt
  tag: 2.11.8
  pullPolicy: Always
service:
  name: scala
  type: NodePort
  port: 7879
volumes:
  ivy2:
    storageClass: default
    accessModes: ReadWriteMany
    size: 2Gi
