{{- if eq .Values.akkaSeed "on" }}
---
apiVersion: v1
kind: Service
metadata:
  name: dev-akka-seeds
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    component: seed
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  clusterIP: None
 {{- end }}
